media:
  input: static/img/blog
  output: /img/blog

content:
  - name: posts
    label: Blog Posts
    path: content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: summary
        label: Summary
        type: string
      - name: cover.image
        label: Cover Image
        type: image
      - name: cover.alt
        label: Cover Image Alt Text
        type: string
      - name: body
        label: Content
        type: rich-text
